// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guhhzmunbuscszzqmulk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1aGh6bXVuYnVzY3N6enFtdWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTk3NTAsImV4cCI6MjA2NTYzNTc1MH0.wAjEl4eqoK8P2K3vRwBXmarTbu_QMLg8sSymvP4aVeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);